version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend/:/usr/src/app
    command: flask run --host=0.0.0.0 --port=5000
    env_file:
      - ./.env
    ports:
      - 5000:5000
  frontend:
    container_name: fronta
    build:
      context: ./front
    volumes:
      - ./front/:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    ports:
      - 3000:3000
